CREATE TABLE dids (
  id INT PRIMARY KEY AUTO_INCREMENT,
  did VARCHAR(20) NOT NULL UNIQUE,
  in_use BOOLEAN DEFAULT FALSE,
  country VARCHAR(50),
  destination VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);