CREATE TABLE phone_numbers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ani VARCHAR(20) NOT NULL,
  dnis VARCHAR(20) NOT NULL,
  country VARCHAR(50),
  carrier VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);